fix WASI & Android build, add to CI and add `Combine` package trait (#406)
* try apple/swift-nio's wasm workflow

... like swift-distributed-tracing [did](https://github.com/apple/swift-distributed-tracing/pull/175/changes)

* WASI doesn't have notification center - ifdef out

* only build specifics to avoid:

```
error: dynamic libraries are unsupported for target 'wasm32-unknown-wasip1'
[3/15] Linking libIssueReportingTestSupport.wasm
```

* add Combine trait to enable/disable combine support

so it can be disabled on non-supported platforms, e.g. currently Android

* add Combine trait & enable by default; add android ci via skiptools

* no building tests on android, supported swift version for ubuntu

* bump combine-schedulers for Linux/OpenCombine support

* fix naming - we're building only

* add OpenCombine dependency & fix Linux build

we're importing the Shim now, which should be available in case
`#if Combine` resolved to true.
It's kind of sad we're leaking

* bump dependencies, add explicit dependency to work around `SwiftCompilerPlugin` not being picked up

I'm not clear why we were seeing:
```/__w/swift-dependencies/swift-dependencies/Tests/DependenciesMacrosPluginTests/DependencyClientMacroTests.swift:1:8: error: missing required module 'SwiftCompilerPlugin'
   1 | import DependenciesMacrosPlugin
     |        `- error: missing required module 'SwiftCompilerPlugin'
   2 | import MacroTesting
   3 | import XCTest
[942/955] Compiling DependenciesMacrosPluginTests BaseTestCase.swift
/__w/swift-dependencies/swift-dependencies/Tests/DependenciesMacrosPluginTests/DependencyClientMacroTests.swift:1:8: error: missing required module 'SwiftCompilerPlugin'
   1 | import DependenciesMacrosPlugin
     |        `- error: missing required module 'SwiftCompilerPlugin'
   2 | import MacroTesting
   3 | import XCTest
[943/955] Compiling DependenciesMacrosPluginTests DependencyEndpointMacroTests.swift
/__w/swift-dependencies/swift-dependencies/Tests/DependenciesMacrosPluginTests/DependencyClientMacroTests.swift:1:8: error: missing required module 'SwiftCompilerPlugin'
   1 | import DependenciesMacrosPlugin
     |        `- error: missing required module 'SwiftCompilerPlugin'
   2 | import MacroTesting
   3 | import XCTest

```

on https://github.com/untitled-in-brackets/swift-dependencies/actions/runs/22952803121/job/66621506036

but hoping being explicit fixes it (and we import, so should be fine?)

* bump swift version to get newest package

* no current 6.3 nightly it seems

* s/true/false/